# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b3d42364b1dd0d4382b8dcf200798ed59b3988f00e1dbb8395a3118851aa0b1fb80cb3829eb89b27b51ab7a0dd421d853a5ab6c58fbd1f4356aeef1f12b4c3

test:
  secret_key_base: 9382503121628310667bc44caf19f408c1c814d9d0d591132513281d764c9ed31e4bb7129ecfecd7c2d992cb48bafdd332e9a094c1b6fe3eaeb982be6c43beb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
